server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${LGHJ_MYSQL_HOST:127.0.0.1}:${LGHJ_MYSQL_PORT:3306}/${LGHJ_MYSQL_DATABASE:lghj}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LGHJ_MYSQL_USERNAME:root}
    password: ${LGHJ_MYSQL_PASSWORD:123456}
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

  task:
    scheduling:
      pool:
        size: 5

  redis:
    host: ${LGHJ_REDIS_HOST:127.0.0.1}
    port: ${LGHJ_REDIS_PORT:6379}
    database: ${LGHJ_REDIS_DATABASE:8}

  elasticsearch:
    uris: ${LGHJ_ES_URIS:http://127.0.0.1:9200}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:com.lghj.mapper/**/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 量股化金接口文档
    description: "量股化金接口文档"
    email: xian@feng.cn
    concat: Feng
    url: https://www.itfeng.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.lghj.controller

lghj:
  jwt:
    admin-secret-key: itfeng
    admin-ttl: 7200000000000
    admin-token-name: token
    user-secret-key: itfeng
    user-ttl: 7200000000000
    user-token-name: token
